### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ford--prefect** [matlink/gplaycli#138] opened 2017-11-20 22:29 UTC
Hi,
on Archlinux 64bit, Python 3.6, gplaycli 3.10 (via setup.py), credentials, I get a fail that looks like an uncaught exception:

> Traceback (most recent call last):
  File "/usr/bin/gplaycli", line 11, in <module>
    load_entry_point('GPlayCli==3.10', 'console_scripts', 'gplaycli')()
  File "/usr/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 513, in main
    cli.prepare_analyse_apks()
  File "/usr/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 213, in prepare_analyse_apks
    self.prepare_download_updates)
  File "/usr/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 233, in analyse_local_apks
    store_version_code = detail['versionCode']
TypeError: 'NoneType' object is not subscriptable

Another user reported something similar, seems not to be an isolated incident.
Will happily provide more info if needed.

**Comment by matlink** [comment] 2017-11-21 06:21
Can you give the command you're using and apks in the folder you're trying to update ?

**Comment by ford--prefect** [comment] 2017-11-21 12:33
I feared this question, since I observed this embedden in my script only so far. I can try to reproduce this in a clean manner, might take some days though…

**Comment by wetterfroschdus** [comment] 2017-11-22 23:48
Hi, i'm getting the same kind of error downloading this app:  "com.tellm.android.app"
After a couple of retries it downloads the apk.

> gplaycli -d com.tellm.android.app
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 11, in <module>
    load_entry_point('GPlayCli==3.10', 'console_scripts', 'gplaycli')()
  File "/usr/local/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 528, in main
    cli.download_packages(args.packages_to_download)
  File "/usr/local/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 399, in download_packages
    self.after_download)
  File "/usr/local/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 291, in download_selection
    vc = detail['versionCode']
TypeError: 'NoneType' object is not subscriptable

**Comment by matlink** [comment] 2017-11-23 14:46
Hum, it seems to be related to python 3.6. Since I'm using 3.5, I was not able to reproduce. I'll dig deeper :)

**Comment by matlink** [comment] 2017-11-27 16:16
Duplicate #126

**Comment by ford--prefect** [comment] 2017-11-27 22:34
The described solution in #126 does not work for me, I am running with credentials and `token=False` but get the error nonetheless.
Also 3.11 does not fix this.

**Comment by matlink** [comment] 2017-12-02 18:54
You have no error when running the 3.2 version of gplaycli?

**Comment by ford--prefect** [comment] 2017-12-02 22:51
Exactly.
I now went back some Versions (jumped from 3.2 to 3.10 before) to test regressions.
Turns out that from 3.7 I see the Nonetype subscription error, 3.6 and earlier shows an `AttributeError: 'GPlaycli' object has no attribute 'token'` (prob. due to a gpapi version mismatch).

I also realize just now that the 3.2 package I am using as fallback is using python2.7.

Sorry for this rather inconsistent error, but this problem clearly is not fixed for me.

**Comment by matlink** [comment] 2017-12-03 15:39
How do you fallback to version 3.2? In this case, which version of `gpapi` are you using?

**Comment by ford--prefect** [comment] 2017-12-03 22:26
Falling back to 3.2 means for me re-installing the package i built. That also means using the python2 version of gpapi wich is 0.1.5 (compared to 0.3.1 for python3).
This is getting more complicated every day.

**Comment by matlink** [comment] 2017-12-08 08:54
The issue is that token expires between Google login and downloading apks.
I'm currently fixing this issue by getting a new token and login again when empty response is detected.
I'll let you try when this is ready.

**Comment by matlink** [comment] 2017-12-08 10:17
I've pushed the fix to the `tokenexpiration` branch.
Could you try again with that branch?

**Comment by ford--prefect** [comment] 2017-12-08 10:30
will test asap, hopefully tonight. Thank you for looking into this, despite my rather messy problem description.

**Comment by matlink** [comment] 2017-12-11 12:18
It has been merge to master in version 3.12 and pushed to pypi.

**Closed by matlink** 2017-12-11 12:18 UTC
