### ISSUE TITLE
Token dispenser error. 502 bad gateway

### ISSUE THREAD

**Issue by ofskymohsen** [matlink/gplaycli#237] opened 2019-12-12 08:44 UTC
- [Ubuntu 18.04 ] Operating System 
- [3] Python version when running `gplaycli` (should be 3+)
- [3.24 ] GPlayCli version via `gplaycli -v`
- [ pip3 install gplaycli] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
- [token ] The authentication method: (own) credentials or (own) token.

When I enter URL `https://matlink.fr/token/email/gsfid` server gives this error:
```
502 Bad Gateway
nginx/1.14.2
```
How can I fix this problem?

**Comment by eighthave** [comment] 2019-12-12 16:06
I also am seeing this error:
```
cache file does not exists or is corrupted
Unknown error: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
```

**Comment by leegarrett** [comment] 2019-12-18 02:59
This is a duplicate of #229.

**Comment by ofskymohsen** [comment] 2019-12-26 15:03
Error message has been changed to this:
```
<html>
   <head></head>
   <body>Auth error</body>
</html>
```

**Comment by quyeticb** [comment] 2020-01-16 10:01
Some method changed by google, (or libcurl error), please update your libcurl.
You also can using some similar online tool (chrome ext, firefox ext...) to download apk
ex: https://chrome.google.com/webstore/detail/aio-apk-downloader/mlipaappcpbepmoeighdkkcfmjeijhdl

**Comment by jr3074** [comment] 2020-01-27 02:28
token dispenser error, there is new fork but i don't know how to implement it on gplaycli @matlink 
https://github.com/whyorean/AuroraDispenser

**Comment by jr3074** [comment] 2020-01-27 13:46
without token dispenser it works (login using user n password)
now, how to get the gsfid and authsubtoken from logged in account and then store it to cache file without token dispenser?

**Comment by mirabilos** [comment] 2020-01-28 23:09
This also happens with the gplaycli version in Debian. Corresponding bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950112

A better error message would help the user to understand that it’s about an external service. Documentation of how to not use that service would also help. Furthermore, it’s probably required by GDPR to inform the user that, upon using gplaycli, it not only connects to Google’s servers but also to those of a third-party, who’s even French.

**Comment by matlink** [comment] 2020-02-11 12:03
@mirabilos Now tokendispenser is returning a 503 with an error message "Token-dispenser is unavailable due to IP blacklisted from Google".

**Comment by matlink** [comment] 2020-02-11 12:18
Duplicate #229

**Closed by matlink** 2020-02-11 12:18 UTC
