### ISSUE TITLE
gpapi.googleplay.LoginError: 'server says: UNKNOWN_ERR'

### ISSUE THREAD

**Issue by LXQBer** [matlink/gplaycli#217] opened 2019-08-30 07:08 UTC
I WON'T ANSWER IF YOU DON'T PROVIDE SUCH DETAILS. COPY-PASTING IS NOT ENOUGH, I'M NOT A JEDI (YET).

Please provide those informations:

- [windows ] Operating System (ie Ubuntu 16.04)
- [python3+ ] Python version when running `gplaycli` (should be 3+)
- [3.25 ] GPlayCli version via `gplaycli -v`
- [ pip3 install gplaycli] The way you installed `gplaycli`: `git clone`, `git clone and setup.py`, `pip install gplaycli`, `apt install gplaycli`, ...
- [gplaycli.conf ] The authentication method: (own) credentials or (own) token.

After testing many times, I suddenly reported an error. gpapi. googleplay. LoginError:'server says: UNKNOWN_ERR'. I can't log in. I don't know how to modify it.

**Comment by delthas** [comment] 2019-08-30 07:52
Hi, this recent issue is probably due to a change in how Google validates authentication requests. See https://github.com/NoMore201/googleplay-api/issues/93.

The way it's done is that gplaycli gets an authentication token from a server hosted at matlink.fr, which runs an instance of [the token dispenser](https://github.com/matlink/token-dispenser/), which uses the [play-store-api library](https://github.com/yeriomin/play-store-api) to make the request. The way to fix it is to fix the play-store-api library (I made [a PR that needs to be merged](https://github.com/yeriomin/play-store-api/pull/40)), then update the token dispenser repository to use the newer play-store-api library, then ask matlink to update his token dispenser server instance.

If you're in a hurry, you can rebuild the token dispenser with [the fixed play-store-api version](https://github.com/delthas/play-store-api/tree/fix-login), and run a local token dispenser instance. In that case make sure to change the `token_url=https://matlink.fr/token/email/gsfid` field in your `gplaycli.conf`.

**Comment by LXQBer** [comment] 2019-08-30 07:58
> 嗨，这个最近的问题可能是由于Google验证身份验证请求的方式发生了变化。见[NoMore201 / googleplay-api＃93](https://github.com/NoMore201/googleplay-api/issues/93)。
> 
> 它的工作方式是gplaycli从matlink.fr托管的服务器获取一个身份验证令牌，该服务器运行[令牌分配器的](https://github.com/matlink/token-dispenser/)一个实例，[该](https://github.com/matlink/token-dispenser/)实例使用[play-store-api库](https://github.com/yeriomin/play-store-api)来发出请求。修复它的方法是修复play-store-api库（我制作[了一个需要合并的PR](https://github.com/yeriomin/play-store-api/pull/40)），然后更新令牌分配器存储库以使用更新的play-store-api库，然后请求matlink更新他的令牌分配服务器实例。
> 
> 如果您赶时间，可以使用[固定的play-store-api版本](https://github.com/delthas/play-store-api/tree/fix-login)重建令牌分配器，并运行本地令牌分配器实例。在这种情况下，请务必更改`token_url=https://matlink.fr/token/email/gsfid`您的字段`gplaycli.conf`。

Thank you very much for your answer, I have found a solution, thank you very much!!!

**Comment by xulifan** [comment] 2019-08-30 16:24
> > 嗨，这个最近的问题可能是由于Google验证身份验证请求的方式发生了变化。见[NoMore201 / googleplay-api＃93](https://github.com/NoMore201/googleplay-api/issues/93)。
> > 它的工作方式是gplaycli从matlink.fr托管的服务器获取一个身份验证令牌，该服务器运行[令牌分配器的](https://github.com/matlink/token-dispenser/)一个实例，[该](https://github.com/matlink/token-dispenser/)实例使用[play-store-api库](https://github.com/yeriomin/play-store-api)来发出请求。修复它的方法是修复play-store-api库（我制作[了一个需要合并的PR](https://github.com/yeriomin/play-store-api/pull/40)），然后更新令牌分配器存储库以使用更新的play-store-api库，然后请求matlink更新他的令牌分配服务器实例。
> > 如果您赶时间，可以使用[固定的play-store-api版本](https://github.com/delthas/play-store-api/tree/fix-login)重建令牌分配器，并运行本地令牌分配器实例。在这种情况下，请务必更改`token_url=https://matlink.fr/token/email/gsfid`您的字段`gplaycli.conf`。
> 
> Thank you very much for your answer, I have found a solution, thank you very much!!!

Hi, Could you please share your solution? I have the same problem. Thanks.

**Comment by matlink** [comment] 2019-09-07 12:43
PLease try again with gplaycli 3.26 and tell me if it is still not working.

**Closed by matlink** 2019-09-07 12:43 UTC

**Comment by kyak** [comment] 2019-11-11 16:20
Hi!

I seem to have the same issue now with 3.26:

    [Arch Linux]
    [Python 3.7.4]
    [GPlayCli version 3.26]
    [AUR]
    [login/app password (two-factor auth set up)]

> Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/gplaycli/gplaycli.py", line 446, in connect_credentials
>     self.api.login(email=self.gmail_address, password=password)
>   File "/usr/lib/python3.7/site-packages/gpapi/googleplay.py", line 224, in login
>     raise LoginError("server says: " + params["error"])
> gpapi.googleplay.LoginError: 'server says: UNKNOWN_ERR'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/gplaycli", line 11, in <module>
>     load_entry_point('GPlayCli==3.26', 'console_scripts', 'gplaycli')()
>   File "/usr/lib/python3.7/site-packages/gplaycli/gplaycli.py", line 709, in main
>     cli.prepare_analyse_apks()
>   File "/usr/lib/python3.7/site-packages/gplaycli/gplaycli.py", line 502, in prepare_analyse_apks
>     to_update = self.analyse_local_apks(list_of_apks, download_folder)
>   File "/usr/lib/python3.7/site-packages/gplaycli/hooks.py", line 8, in check_connection
>     self.connect()
>   File "/usr/lib/python3.7/site-packages/gplaycli/gplaycli.py", line 420, in connect
>     return self.connect_credentials()
>   File "/usr/lib/python3.7/site-packages/gplaycli/gplaycli.py", line 448, in connect_credentials
>     logger.error("Bad authentication, login or password incorrect (%s)", login_error)
> NameError: name 'login_error' is not defined

**Comment by kyak** [comment] 2019-11-17 10:37
@matlink This is still an issue with 3.26. Please let me know if you need more information to figure out the cause of the problem. I haven't been able to update my apks in days now :(
