### ISSUE TITLE
Error with getDefaultHeaders from gpapi

### ISSUE THREAD

**Issue by gzeuro** [matlink/gplaycli#130] opened 2017-11-12 13:50 UTC
- [14.04.5] Operating System
- [Python3.4.3] Python version
- [3.10] GPlayCli version
- [pip3 install gplaycli] The way you installed `gplaycli`
- [token] The authentication method

Config file:

[Credentials]
gmail_address=
gmail_password=
#keyring_service=gplaycli
android_ID=3d716411bf8bc802
language=fr_FR
token=True
token_url=https://matlink.fr/token/email/gsfid

[Cache]
token=/opt/bitnami/apache2/htdocs/core/1.0/pyt/gplaycli/token/token

I'm getting this issue, e.g. for `/usr/local/bin/gplaycli -c /opt/bitnami/apache2/htdocs/core/1.0/pyt/gplaycli/gplaycli.conf -v -s com.ubercab` with PHP shell_exec():

[INFO] GPlayCli version 3.10 [Python3.4.3] 
[INFO] Configuration file is ['/opt/bitnami/apache2/htdocs/core/1.0/pyt/gplaycli/gplaycli.conf']
[INFO] Retrieving token ...
[INFO] Starting new HTTPS connection (1): matlink.fr
[INFO] Token: ZgUcMT_XHew2vtmS2ReCjPvEV3qj1p3dnM3uTCDRM4zK9Hzm6xh0AjyVusLJ3xLvFCwTNA.
[INFO] GSFId: 3c3dd10074514b9c
[INFO] Using token to connect to API
Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 9, in <module>
    load_entry_point('GPlayCli==3.10', 'console_scripts', 'gplaycli')()
  File "/usr/local/lib/python3.4/dist-packages/gplaycli/gplaycli.py", line 504, in main
    success, error = cli.connect_to_googleplay_api()
  File "/usr/local/lib/python3.4/dist-packages/gplaycli/gplaycli.py", line 194, in connect_to_googleplay_api
    gsfId=gsfId)
  File "/usr/local/lib/python3.4/dist-packages/gpapi/googleplay.py", line 191, in login
    self.search('firefox', 1, None)
  File "/usr/local/lib/python3.4/dist-packages/gpapi/googleplay.py", line 296, in search
    data = self.executeRequestApi2(currentPath)
  File "/usr/local/lib/python3.4/dist-packages/gpapi/googleplay.py", line 253, in executeRequestApi2
    headers = self.getDefaultHeaders()
  File "/usr/local/lib/python3.4/dist-packages/gpapi/googleplay.py", line 89, in getDefaultHeaders
    "Accept-Language": self.deviceBuilder.locale.replace('_', '-'),
AttributeError: 'NoneType' object has no attribute 'replace'

I've upgraded an older (working) version of gplaycli to 3.10, but get the same error also on fresh installations (with Ubuntu and Amazon Linux, different Locales and from different IP addresses). 

Thank you very much for your help!

**Comment by gzeuro** [comment] 2017-11-12 17:03
Okay, after changing line 89 in gpapi\googleplay.py from 
`"Accept-Language": self.deviceBuilder.locale.replace('_', '-'),` to
`"Accept-Language": "en-US",` the PHP output works now for me.

Occasionally I get the same error as described by wetterfroschdus in [#128](https://github.com/matlink/gplaycli/issues/128) and have to delete the token file first (with version 3.10).

**Comment by NoMore201** [comment] 2017-11-13 11:09
Fixed in [gpapi 0.3](https://github.com/NoMore201/googleplay-api/releases/tag/v0.3)

**Comment by gzeuro** [comment] 2017-11-13 22:20
With gpapi 0.3 I get this error now (calling gplaycli from PHP):

Traceback (most recent call last):
  File "/usr/local/bin/gplaycli", line 9, in <module>
    load_entry_point('GPlayCli==3.10', 'console_scripts', 'gplaycli')()
  File "/usr/local/lib/python3.4/dist-packages/gplaycli/gplaycli.py", line 504, in main
    success, error = cli.connect_to_googleplay_api()
  File "/usr/local/lib/python3.4/dist-packages/gplaycli/gplaycli.py", line 169, in connect_to_googleplay_api
    self.playstore_api = GooglePlayAPI(device_codename=self.device_codename)
  File "/usr/local/lib/python3.4/dist-packages/gpapi/googleplay.py", line 55, in __init__
    self.deviceBuilder.setLocale(locale)
  File "/usr/local/lib/python3.4/dist-packages/gpapi/config.py", line 62, in setLocale
    if match(r'[a-z]{2}\_[A-Z]{2}', locale) is None:
  File "/usr/lib/python3.4/re.py", line 160, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer

**Comment by NoMore201** [comment] 2017-11-13 23:19
@gzeuro opening a python interactive shell, can you post the output of these commands?
```
import locale
locale.getdefaultlocale()
```

**Comment by gzeuro** [comment] 2017-11-14 00:21
**@NoMore201**
`>>> import locale`
`>>> locale.getdefaultlocale()`
`('en_US', 'UTF-8')`

PHP locale_get_default() echos `en_US_POSIX`, maybe that's the problem?

**Comment by NoMore201** [comment] 2017-11-14 10:29
The output of `locale.getdefaultlocale()` seems ok, the only requirement for gpapi is that it should be a string. The problem could be caused by

- `getdefaultlocale()` returning None, in the environment where gplaycli is run
- GooglePlayAPI is initialized with a non-string value for locale, but I don't think it's the case with gplaycli

I thightened checks in latest commit , now it should cover all these cases.

**Closed** 2017-11-27 16:09 UTC
